name: "ONNX-embedding-multilingual-e5-large-instruct" 
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
    {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: [-1]
    },
    {
        name: "attention_mask"
        data_type: TYPE_INT64
        dims: [-1]
    }
]

output [
    {
        name: "sentence_embedding"
        data_type: TYPE_FP32
        dims: [1024]
    },
    {
        name: "token_embeddings"
        data_type: TYPE_FP32
        dims: [-1, 1024]
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 100
}

response_cache {
  enable: true
}

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]